const miTelefono = "573156016386";

const productos = [
    {
        id: 2,
        nombre: "PDFs Downloader (DIAN)",
        url: "pdfs-downloader.html",
        formato: "Extensión Web .crx",
        mostrarTecnica: true,
etiqueta: "¡EN PRODUCCION!",
        desc: "<b>REF006</b> <p>Accede y descarga documentos electrónicos en PDF directamente desde la DIAN de forma rápida, sencilla y sin procesos manuales. Dile adiós a las interrupciones; nuestra herramienta se encarga de validar los captchas y de ingresar el NIT correspondiente, optimizando tu flujo de trabajo al máximo.<p><b>Publicada el 03-08-2026</b>",
        caracteristicas: ["<p><b>Cero trámites adicionales:</b> No necesitas generar Token ni adquirir un Certificado Digital de la DIAN para descargar tus PDFs.<p>","Módulo Descarga PRO (Multidocumento): Carga tu plantilla de Excel con los códigos (CUDE, CUDS, CUFE, CUNE) y su respectivo NIT. El sistema procesa de forma automatizada (entre 3 y 9 segundos por documento) eludiendo los captchas y entregando los PDFs listos para visualizar, sin contraseñas.", "Módulo Descarga F.E. (Ultrarrápido): Descarga masiva de Facturas Electrónicas y Notas a una velocidad increíble de 0.5 segundos por documento. Sin captchas, sin NIT y sin contraseñas. Solo carga tu Excel o pega los CUFES directamente.", "Módulo Tools (Gestión y Exportación): Toma el control total de tus archivos. Renombra tus PDFs de forma masiva, extrae la información clave, lístala y expórtala directamente a Excel para tus cruces e informes."],
        nota: "Para brindarle un soporte técnico oportuno, requerimos conectarnos de forma remota a su equipo a través de AnyDesk. Tenga en cuenta que este acceso quedará registrado de manera individual en cada computadora durante la instalación. Por su seguridad, nuestro equipo se comunicará exclusivamente al número de móvil que tiene registrado con nosotros. Asimismo, le recordamos que el funcionamiento de nuestra herramienta depende de plataformas de terceros integradas; <b>cualquier cambio en los parámetros de dichas plataformas nos exime de responsabilidad sobre la continuidad del servicio.</b>",
        precio: "COP $50.000",
        video: "video/Pdfs.mp4",
        youtube: "https://youtu.be/hiZn2nFgtX4",
        fotos: ["img/p2-0.png", "img/p2-1.png", "img/p2-2.jpg","img/p2-3.png"]
    },           
{
        id: 12,
        nombre: "Reportes Renta P.N A.G2025 (DIAN)",
        url: "reporte-rentapn.html",
        formato: "Extensión Web .crx",
        mostrarTecnica: true,
        etiqueta: "NUEVO",
        desc: "<b>REF002</b><p>Ahorra tiempo en esta temporada de Renta de Personas Naturales (Año Gravable 2025). Descarga y renombra automáticamente tus listados de facturas electrónicas y exógena sugerida para una validación rápida, precisa y sin esfuerzo de reportes desde periodos 2013 a 2025.<p> <p>Además puedes iniciar el aplicativo y elegir las 3 opciones de descarga,mientras estas en la sesión del contribuyente.<p><b>Actualizada el 19-07-2026</b>",
        caracteristicas: ["Inicia sesión del contribuyente.", "Puedes descargar masivamente reportes de exógena sugerida.", "Puedes descargar masivamente reportes factura electrónica y sus PDF's.", "Puedes descarga masivamente formularios 110/210 presentados.","Analizador tributario de exógena", "Esta herramienta es de apoyo para la temporada Agto a Oct 2026."],
        nota: "Para brindarle un soporte técnico oportuno, requerimos conectarnos de forma remota a su equipo a través de AnyDesk. Tenga en cuenta que este acceso quedará registrado de manera individual en cada computadora durante la instalación. Por su seguridad, nuestro equipo se comunicará exclusivamente al número de móvil que tiene registrado con nosotros. Asimismo, le recordamos que el funcionamiento de nuestra herramienta depende de plataformas de terceros integradas; <b>cualquier cambio en los parámetros de dichas plataformas nos exime de responsabilidad sobre la continuidad del servicio.</b>",
        precio: "COP $20.000",
        video: "video/ReportePN.mp4",
        youtube: "https://youtu.be/qa_wJjN3Nvo",
        fotos: ["img/p12-0.png", "img/p12-1.png", "img/p12-2.png", "img/p12-3.png"]
    },        
{
        id: 7,
        nombre: "WiCONTABLE Lite",
        url: "wicontable-lite.html",
        formato: "Ejecutable .exe",
        mostrarTecnica: true,
etiqueta: "¡EN PRODUCCION!",
        desc: "<b>REF001</b><p>La primera solución pensada para contadores y profesionales financieros que permite consultar de manera masiva en 4 plataformas claves: DIAN, PROCURADURIA, RUES Y SISBÉN.<p><b>Actualizada el 27-11-2025</b>",
        caracteristicas: ["Ideal para temporada de Exogena podras validar los nombres asociados a los Nit ó cualquier tipo de documento que permitan las plataformas.", "Organiza tus obligaciones tributarias en el entorno calendario.", "Localmente podras convertir Imagen a PDF, Unir PDF y aplicar OCR.", "Accede aun repositorio contable amplio para estar al día."],
        nota: "Para brindarle un soporte técnico oportuno, requerimos conectarnos de forma remota a su equipo a través de AnyDesk. Tenga en cuenta que este acceso quedará registrado de manera individual en cada computadora durante la instalación. Por su seguridad, nuestro equipo se comunicará exclusivamente al número de móvil que tiene registrado con nosotros. Asimismo, le recordamos que el funcionamiento de nuestra herramienta depende de plataformas de terceros integradas; cualquier cambio en los parámetros de dichas plataformas nos exime de responsabilidad sobre la continuidad del servicio.</b>",
        precio: "COP $79.900",
        video: "video/WiCONTABLELite.mp4",
        youtube: "https://youtu.be/cVeRtfur7X4",
        fotos: ["img/p7-0.png", "img/p7-1.png", "img/p7-2.png", "img/p7-3.png", "img/p7-4.png", "img/p7-5.png", "img/p7-6.png", "img/p7-7.png", "img/p7-8.png", "img/p7-9.png", "img/p7-10.png"]
    },        
        {
        id: 13,
        nombre: "WiCONTABLE Auditor F.E (DIAN)",
        url: "auditor-fe.html",
        formato: "Extensión Web .crx",
        mostrarTecnica: true,
etiqueta: "¡EN PRODUCCION!",
        desc: "<b>REF003</b><p>Optimice la gestión tributaria y asegure el cumplimiento normativo de su empresa con nuestra herramienta avanzada para la validación masiva de eventos, el análisis de archivos XML y la descarga automatizada de facturas electrónicas directamente desde el portal de la DIAN.<p> <p><b>¿Te preocupan los nuevos bloqueos anti-bot de la DIAN y el impacto que tendrán en tus costos operativos? No te preocupes. Hemos diseñado un método exclusivo que te permite seguir operando con normalidad, sin la necesidad de comprar certificados adicionales. Protege tu presupuesto y simplifica tus procesos con nosotros.<p></b> <p>WiCONTABLE Auditor F.E (DIAN) le permite rastrear en tiempo real el ciclo de vida completo de cada documento, identificando al instante si una factura ha sido recibida, reclamada, aceptada, rechazada o si ya circula en el mercado financiero como título valor a través de la plataforma RADIAN. En el panorama fiscal actual, la gestión de los comprobantes electrónicos ha dejado de ser un simple requerimiento de facturación para convertirse en un pilar del flujo de caja corporativo y de la deducción de costos y gastos.<p> <p>Además de ahorrarle tiempo al determinar qué ítem, qué impuesto y qué datos están asociados a cada factura, la herramienta le permite visualizar todo el detalle directamente desde su equipo o desde la sesión del contribuyente a partir del archivo XML.<p><b>Lanzamiento el XX-08-2026</b>",
        caracteristicas: ["Descargue los archivos PDF de sus F.E sin requerir Token ni Certificado Digital.", "Valide eventos asociados a documentos electrónicos sin requerir Token ni Certificado Digital.", "Renombre masivamente sus archivos XML y PDF al descargarlos.", "Realice una validación avanzada de eventos en sus F.E, aprovechando la conexión directa que le brinda su Token.", "Potencie la descarga de archivos PDF/XML de sus F.E utilizando su Token y realizandolo completamente por rangos.", "Olvídese de trámites complejos; nuestra solución trabaja sin Certificado Digital."],
        nota: "<p>Para brindarle un soporte técnico oportuno, requerimos conectarnos de forma remota a su equipo a través de AnyDesk.<p> <p>Tenga en cuenta que este acceso quedará registrado de manera individual en cada computadora durante la instalación; por su seguridad, nuestro equipo se comunicará exclusivamente al número de móvil que tiene registrado con nosotros.<p> <p>Asimismo, le recordamos que el funcionamiento de nuestra herramienta depende de plataformas de terceros integradas; <b>cualquier cambio en los parámetros de dichas plataformas nos exime de responsabilidad sobre la continuidad del servicio.</b><p> <p>Para agilizar el proceso de instalación, le recomendamos ver previamente el videotutorial de funcionamiento. De esta manera, podremos optimizar el tiempo de la sesión y enfocarnos en resolver dudas específicas durante las pruebas de funcionalidad y la entrega final de la herramienta.<p>",
        precio: "COP $100.000",
        video: "video/WiCONTABLE.mp4",    
        youtube: "https://www.youtube.com/watch?v=tWS24jBXEkc",
        fotos: ["img/p13-0.png", "img/p13-1.png", "img/p13-2.png", "img/p13-3.png", "img/p13-4.png", "img/p13-5.png"]
    },
    {
        id: 3,
        nombre: "Consulta Datos NIT (DIAN)",
        url: "consulta-datos-nit.html",
        formato: "Extensión Web .crx",
        mostrarTecnica: true,
etiqueta: "ACTIVA",
        desc: "<b>REF005</b><p>Verifica de forma masiva, automática y directamente en el portal DIAN el nombre asociado a los NIT de contribuyente Persona Juridica ó Persona Natural suscritos, sin procesos manuales ni captchas repetitivos.<p> <p>Ideal para temporada de exógena y validación de los formatos que requieran esta auditoria.<p><b>Actualizada el 05-01-2026</b>",
        caracteristicas: ["Carga un archivo EXCEL ó pega directamente las identificaciones.", "Puedes decidir en consultar CON estado RUT, la cual te anexara si esta: ACTIVO, CANCELADO ó SUSPENDIDO; este proceso valida catpcha y depende si el portal web se encuentre estable.", "Puedes decidir en consultar SIN estado RUT, la cual es más ligero y estable; este proceso solo te indica si esta registrado o no en la DIAN."],
        nota: "Para brindarle un soporte técnico oportuno, requerimos conectarnos de forma remota a su equipo a través de AnyDesk. Tenga en cuenta que este acceso quedará registrado de manera individual en cada computadora durante la instalación. Por su seguridad, nuestro equipo se comunicará exclusivamente al número de móvil que tiene registrado con nosotros. Asimismo, le recordamos que el funcionamiento de nuestra herramienta depende de plataformas de terceros integradas; cualquier cambio en los parámetros de dichas plataformas nos exime de responsabilidad sobre la continuidad del servicio.</b>",
        precio: "COP $30.000",
        video: "video/RUT2026.mp4",
        youtube: "https://www.youtube.com/watch?v=1wLEFzIwj38",
        fotos: ["img/p3-0.png", "img/p3-1.jpg"]
    }, 



       
{
        id: 6,
        nombre: "Gemini PRO (18 Meses)",
        url: "gemini-pro.html",
        formato: "Credenciales",
        mostrarTecnica: false,
etiqueta: "DISPONIBLE",
        desc: "Disfruta de 18 meses completos de Gemini PRO, con acceso a las funciones avanzadas de inteligencia artificial de Google, además de los beneficios incluidos con la promoción de Jio.<p><b> </b><p>",
        caracteristicas: ["Acceso a Gemini Pro.", "Modelos de IA avanzados para mayor rendimiento.", "Ayuda en redacción, programación, estudio y productividad.", "Generación de contenido y asistencia inteligente.", "Beneficios adicionales incluidos con la promoción de Jio 5TB de espacio.", "Se entrega un link vía anydesk listo para canjear el beneficio." ,"Disponible desde navegador web, Android y dispositivos compatibles con los servicios de Google."],
        nota: "Te encuenta las siguientes recomendaciones: <b>El enlace es de un solo uso.</b> Se recomienda canjearlo únicamente en la cuenta de Google donde deseas disfrutar el beneficio; Una vez activado correctamente, el servicio quedará asociado a tu cuenta gmail. <b>Te realizamos acompañamiento vía Anydesk, para ello tenerlo instalado para poder proceder y para validar una correcta activación, es importante que estes en un PC, no es valido ni en Tablet, ni celular para el acompañamiento.</b> Aplica solo para cliente que puedan realizar el pago con plataformas Colombia. <b>Tener en cuenta que se brinda garantia por 3 meses y que solo se procede si podemos asistir vía anydesk, de lo contrario no hay garantía.</b>",
        precio: "COP $30.000",
        video: "video/Gemini.mp4",
        youtube: "https://youtu.be/IVZaqCdm5XY",
        fotos: ["img/p6-0.png", "img/p6-1.png", "img/p6-2.png", "img/p6-3.png", "img/p6-4.png", "img/p6-5.png", "img/p6-6.png", "img/p6-7.png"]
    },
{
        id: 4,
        nombre: "Microsoft 365 Genuina (1 año)",
        url: "365-office.html",
        formato: "Credenciales",
        mostrarTecnica: false,
etiqueta: "DISPONIBLE",
        desc: "<b>REF004-0</b><p>Activa tu suite de Office de forma segura mediante credenciales corporativas y olvídate de parches o cracks que ponen en riesgo la seguridad de tu PC. <b>Nota importante:</b> Tu cuenta incluye beneficios adicionales como 100 GB de almacenamiento en la nube. Te sugerimos usar este espacio únicamente para archivos no críticos o temporales. El objetivo principal de esta credencial, y donde su efectividad está garantizada al 100 %, es para la activación y uso de Office en su versión de escritorio.<p><b> </b>",
        caracteristicas: ["Activación en hasta 5 dispositivos.", "Compatible con PC / MacOS / Android / iOS.", "IA vía web para mayor productividad", "Tendras acceso a PowerBI Service." , "Word, Excel, y PowerPoint"],
        nota: "Se entrega un correo corporativo con una clave temporal. El usuario es responsable de asignar su propia clave personalizada. La credencial tiene un costo de pago único. En caso de pérdida de la clave creada por el usuario, no será posible recuperar el acceso, <b>se brinda apoyo para la instalación de manera remota mediante AnyDesk.</b> (Recuerde guardar la contraseña que asignó para su respectiva garantía de 1 año, para uso de Word, Excel y PowerPoint.)",
        precio: "COP $30.000",
        video: "video/365.mp4",
        youtube: "https://youtu.be/jKVPmmDu1-I",
        fotos: ["img/p4-0.png", "img/p4-1.png", "img/p4-2.png"]
    },
{
        id: 14,
        nombre: "Microsoft 365 Familia (1 año) ADMIN",
        url: "365-officefamilia.html",
        formato: "Credenciales",
        mostrarTecnica: false,
etiqueta: "¡AGOTADO!",
        desc: "<b>REF004-1</b><p>Obtén acceso completo a la suite oficial de Microsoft, la solución ideal para potenciar tu productividad en el estudio o el trabajo. <b>Nota importante:</b> Tu cuenta incluye beneficios adicionales como 1 TB de almacenamiento en la nube, puedes invitar a 5 personas más. Desde la configuración de la cuenta principal, el Administrador puede enviar un enlace de invitación a hasta 5 familiares o amigos. Nadie puede ver los archivos o correos de los demás. El almacenamiento de OneDrive y los datos de Word/Excel son 100% privados para cada miembro. El objetivo principal de esta credencial, y donde su efectividad está garantizada al 100 %, es para la activación y uso de Office en su versión de escritorio.<p><b> </b>",
        caracteristicas: ["Para PC, Mac, iPhone, iPad y teléfonos y tabletas Android", "Hasta 1 TB de almacenamiento en la nube", "Copilot Chat avanzado con mayor uso que la versión gratuita", "Usa Copilot en aplicaciones específicas con archivos de trabajo de forma segura" , "Mayor uso para crear imágenes de IA", "Videollamadas durante todo el día y Copilot en Teams" , "Disfruta de las últimas funciones y parches de seguridad durante todo el año de servicio."],
        nota: "Se entrega un correo corporativo con su respectiva clave. La credencial tiene un costo de pago único. En caso de pérdida de la clave creada por el usuario, no será posible recuperar el acceso, <b>se brinda apoyo para la instalación de manera remota mediante AnyDesk.</b> (Recuerde guardar la contraseña que asignó para su respectiva garantía de 7 meses, para uso de Word, Excel y PowerPoint.)",
        precio: "COP $90.000",
        video: "",
        youtube: "",
        fotos: ["img/p14-0.png", "img/p14-1.png", "img/p14-2.png"]
    },
{
        id: 9,
        nombre: "Anydesk V.6.0 (Vitalicia)",
        url: "anydesk-v6.html",
        formato: "Ejecutable .exe",
        mostrarTecnica: false,
etiqueta: "DISPONIBLE",
        desc: "El software de escritorio remoto de alto rendimiento que permite compartir el escritorio sin latencia, un control remoto estable y una transmisión de datos rápida y segura entre dispositivos.<p><b> </b><p>",
        caracteristicas: ["Vea y controle la pantalla de otro dispositivo.", "No requiere licencia y puedes usarlo si formateas tu PC en el futuro.", "Acceda a su dispositivo remoto mediante contraseña sin tener que aceptar la sesión remota manualmente."],
        nota: "Se trata de una aplicación ejecutable (EXE) que ha sido ajustada para mantener siempre la sesión activa y sin limites de tiempo; la aplicación se mantiene operativa de forma indefinida. <b>Se recomienda no actualizar y mantener la versión inicial.</b> En caso que el usuario tenga alguna versión instalada anteriormente se recomienda limpiar los registros mediante regedit para el óptimo funcionamiento de esta versión.",
        precio: "COP $20.000",
        video: "",
        fotos: ["img/p9-0.png"]
    },
 {
        id: 8,
        nombre: "Windows 10/11 PRO (Vitalicia)",
        url: "windows-10-11.html",
        formato: "Credenciales",
        mostrarTecnica: false,
etiqueta: "DISPONIBLE",
        desc: "<b>REF000</b><p>Activa de forma segura con credenciales corporativas y evita el uso de parches o cracks que comprometen la seguridad de tu PC.<p><b> </b>",
        caracteristicas: ["Ingresa la clave digital asignada y listo."],
        nota: "Se entrega la clave al usuario final, quien es responsable de su buen uso. La clave permanece operativa de manera indefinida, garantizando acceso continuo y seguridad en todo momento. <b>único pago.</b> se brinda apoyo para la instalación de manera remota mediante AnyDesk.",
        precio: "COP $20.000",
        video: "",
        fotos: ["img/p8-0.png", "img/p8-1.png"]
    },
{
        id: 1,
        nombre: "ChatGPT PLUS (30 Días)",
        url: "chatgpt-plus.html",
        formato: "Credenciales",
        mostrarTecnica: false,
etiqueta: "DISPONIBLE",
        desc: "Disfruta de acceso completo a las funciones avanzadas de Inteligencia Artificial con una cuenta lista para usar durante 30 días completos. Potencia tu productividad, crea contenido, analiza datos y accede a los modelos más rápidos y actualizados sin interrupciones.<p><b> </b><p>",
        caracteristicas: ["Se entrega un correo electrónico, contraseña única y su respectiva url de código de autenticación.", "Cobertura y soporte garantizado durante 15 días ante cualquier inconveniente.", "Acceso total desde el navegador de tu computadora, celulares y la aplicación oficial."],
        nota: "No cambiar los datos de la cuenta: Está totalmente prohibido modificar el correo, la contraseña o los métodos de pago asociados. <b>El incumplimiento de esta norma cancelará de forma inmediata la garantía de tu servicio sin derecho a reemplazo ni reembolso.</b> Se garantiza durante 15 días ante cualquier inconveniente.",
        precio: "COP $40.000",
        video: "video/ChatGPTPlus.mp4",
        fotos: ["img/p1-0.png", "img/p1-1.png", "img/p1-2.png", "img/p1-3.png", "img/p1-4.png"]
    },
{
        id: 11,
        nombre: "Declaración de Renta P.N.",
        url: "declaracion-renta-pn.html",
        formato: "Consultoria Contable",
        mostrarTecnica: false,
etiqueta: "DISPONIBLE",
        desc: "Brindamos consultoría integral para la elaboración y presentación de tu declaración de renta, asegurando el cumplimiento legal y la optimización de tus impuestos.",
        caracteristicas: ["Diagnóstico inicial de requisitos según topes de la DIAN.", "Análisis de deducciones y beneficios tributarios para pagar lo justo.", "Elaboración del borrador y formulario 110/210.", "Acompañamiento en el proceso de pago y firma electrónica.", "Entrega de informe detallado de la declaración presentada.", "Consulta si estas reportado en  https://webazure.dian.gov.co/consultarenta/"],
        nota: "El valor del servicio puede variar según la complejidad de la realidad financiera del contribuyente (cantidad de bienes, inversiones, etc.). <b>¡Contáctanos para una cotización personalizada!</b>",
        precio: "Desde COP $300.000",
        video: "",
        fotos: ["img/p11-0.png", "img/p11-1.png"]
    },    
    {
        id: 10,
        nombre: "Plataformas/Membresías",
        url: "plataforma-membresias.html",
        formato: "Credenciales",
        mostrarTecnica: false,
etiqueta: "DISPONIBLE",
        desc: "Te invitamos a visualizar nuestro catalogo de ocio, producción y entretenimiento con los mejores precios del mercado.<p><b> </b><p>",
        caracteristicas: ["Plataformas Streaming.", "Antivirus.", "IA.", "VPN.", "Diseño.", "Cursos.", "Juegos"],
        nota: "(En ver videotutorial encontrarás lista de precios y plataformas) Las membresias son en la mayoria mensuales y otras con oferta de hasta 3 y 12 meses. <b>Escribenos y podemos ampliar la información de interes.</b>",
        precio: "Desde COP $1.500",
        video: "https://acortar.link/Plataformax",
        fotos: ["img/p10-0.png"]
    }
];
