const miTelefono = "573156016386";

const productos = [
{
        id: 2,
        nombre: "PDFs Downloader (DIAN)",
        formato: "Extensión Web.crx",
        mostrarTecnica: true,
etiqueta: "ACTIVA",
        desc: "<b>REF006</b> <p>Accede y descarga cualquier documento electrónico en PDF directamente desde la DIAN de forma rápida, sencilla y sin procesos manuales innecesarios.<p><b>Actualizada el 28-12-2025</b>",
        caracteristicas: ["No necesitas generar TOKEN, ni Certificado Digital DIAN para la descarga PDFs.","Carga un archivo EXCEL ó pega directamente los CUDE, CUDS, CUFE, CUNE.", "Procesa en tiempo de respuesta según captcha de 3, 6, 9 segundos por documento.", "Extra aplicativo (WiPDFs) para desbloquear vista previa, renombrar nómina y listar archivos."],
        nota: "Para brindarle un soporte técnico oportuno, requerimos conectarnos de forma remota a su equipo a través de AnyDesk. Tenga en cuenta que este acceso quedará registrado de manera individual en cada computadora durante la instalación. Por su seguridad, nuestro equipo se comunicará exclusivamente al número de móvil que tiene registrado con nosotros. Asimismo, le recordamos que el funcionamiento de nuestra herramienta depende de plataformas de terceros integradas; cualquier cambio en los parámetros de dichas plataformas nos exime de responsabilidad sobre la continuidad del servicio.</b>",
        precio: "COP $30.000",
        video: "https://www.youtube.com/watch?v=hiZn2nFgtX4&t",
        fotos: ["img/p2-0.png", "img/p2-1.png", "img/p2-2.jpg","img/p2-3.png"]
    },
{
        id: 7,
        nombre: "WiCONTABLE Lite",
        formato: "Ejecutable .exe",
        mostrarTecnica: true,
etiqueta: "ACTIVA",
        desc: "<b>REF001</b><p>La primera solución pensada para contadores y profesionales financieros que permite consultar de manera masiva en 4 plataformas claves: DIAN, PROCURADURIA, RUES Y SISBÉN.<p><b>Actualizada el 27-11-2025</b>",
        caracteristicas: ["Ideal para temporada de Exogena podras validar los nombres asociados a los Nit ó cualquier tipo de documento que permitan las plataformas.", "Organiza tus obligaciones tributarias en el entorno calendario.", "Localmente podras convertir Imagen a PDF, Unir PDF y aplicar OCR.", "Accede aun repositorio contable amplio para estar al día."],
        nota: "Para brindarle un soporte técnico oportuno, requerimos conectarnos de forma remota a su equipo a través de AnyDesk. Tenga en cuenta que este acceso quedará registrado de manera individual en cada computadora durante la instalación. Por su seguridad, nuestro equipo se comunicará exclusivamente al número de móvil que tiene registrado con nosotros. Asimismo, le recordamos que el funcionamiento de nuestra herramienta depende de plataformas de terceros integradas; cualquier cambio en los parámetros de dichas plataformas nos exime de responsabilidad sobre la continuidad del servicio.</b>",
        precio: "COP $79.900",
        video: "https://youtu.be/cVeRtfur7X4",
        fotos: ["img/p7-0.png", "img/p7-1.png", "img/p7-2.png", "img/p7-3.png", "img/p7-4.png", "img/p7-5.png", "img/p7-6.png", "img/p7-7.png", "img/p7-8.png", "img/p7-9.png", "img/p7-10.png"]
    },
    {
        id: 3,
        nombre: "Consulta Datos NIT (DIAN)",
        formato: "Extensión Web .crx",
        mostrarTecnica: true,
etiqueta: "ACTIVA",
        desc: "<b>REF005</b><p>Verifica de forma masiva, automática y directamente en el portal DIAN el nombre asociado a los NIT de contribuyente Persona Juridica ó Persona Natural suscritos, sin procesos manuales ni captchas repetitivos.<p> <p>Ideal para temporada de exógena y validación de los formatos que requieran esta auditoria.<p><b>Actualizada el 05-01-2026</b>",
        caracteristicas: ["Carga un archivo EXCEL ó pega directamente las identificaciones.", "Puedes decidir en consultar CON estado RUT, la cual te anexara si esta: ACTIVO, CANCELADO ó SUSPENDIDO; este proceso valida catpcha y depende si el portal web se encuentre estable.", "Puedes decidir en consultar SIN estado RUT, la cual es más ligero y estable; este proceso solo te indica si esta registrado o no en la DIAN."],
        nota: "Para brindarle un soporte técnico oportuno, requerimos conectarnos de forma remota a su equipo a través de AnyDesk. Tenga en cuenta que este acceso quedará registrado de manera individual en cada computadora durante la instalación. Por su seguridad, nuestro equipo se comunicará exclusivamente al número de móvil que tiene registrado con nosotros. Asimismo, le recordamos que el funcionamiento de nuestra herramienta depende de plataformas de terceros integradas; cualquier cambio en los parámetros de dichas plataformas nos exime de responsabilidad sobre la continuidad del servicio.</b>",
        precio: "COP $30.000",
        video: "https://www.youtube.com/watch?v=1wLEFzIwj38",
        fotos: ["img/p3-0.png", "img/p3-1.jpg"]
    },
{
        id: 1,
        nombre: "ChatGPT PLUS (30 Días)",
        formato: "Credenciales",
        mostrarTecnica: false,
etiqueta: "NUEVO",
        desc: "Disfruta de acceso completo a las funciones avanzadas de Inteligencia Artificial con una cuenta lista para usar durante 30 días completos. Potencia tu productividad, crea contenido, analiza datos y accede a los modelos más rápidos y actualizados sin interrupciones.<p><b> </b><p>",
        caracteristicas: ["Datos de acceso: Se entrega un correo electrónico y su respectiva contraseña única.", "Garantía: Cobertura y soporte garantizado durante 20 días ante cualquier inconveniente.", "Compatibilidad: Acceso total desde el navegador de tu computadora, celulares y la aplicación oficial."],
        nota: "No cambiar los datos de la cuenta: Está totalmente prohibido modificar el correo, la contraseña o los métodos de pago asociados. <b>El incumplimiento de esta norma cancelará de forma inmediata la garantía de tu servicio sin derecho a reemplazo ni reembolso.</b>",
        precio: "COP $30.000",
        video: "",
        fotos: ["img/p1-0.png", "img/p1-1.png", "img/p1-2.png"]
    },{
        id: 4,
        nombre: "Microsoft 365 (Vitalicia)",
        formato: "Credenciales",
        mostrarTecnica: false,
etiqueta: "¡NUEVO!",
        desc: "<b>REF004</b><p>Activa de forma segura con credenciales corporativas y evita el uso de parches o cracks que comprometen la seguridad de tu PC.<p><b> </b>",
        caracteristicas: ["Activación en hasta 5 dispositivos.", "Vitalicia.", "Compatible con PC / Android / iOS.", "100 GB de almacenamiento.", "IA vía web para mayor productividad", "Tendras acceso a PowerBI Service." , "Toda la suite 365 para sacar el masivo provecho en el día a día laboral."],
        nota: "Se entrega un correo corporativo con una clave temporal. El usuario es responsable de asignar su propia clave personalizada. La credencial tiene un costo de pago único. En caso de pérdida de la clave creada por el usuario, no será posible recuperar el acceso, <b>se brinda apoyo para la instalación de manera remota mediante AnyDesk.</b> (Recuerde guardar la contraseña que asignó para su respectiva garantía.)",
        precio: "COP $30.000",
        video: "https://youtu.be/jKVPmmDu1-I",
        fotos: ["img/p4-0.png", "img/p4-1.png", "img/p4-2.png"]
    },
    {
        id: 8,
        nombre: "Windows 10/11 PRO (Retail)",
        formato: "Credenciales",
        mostrarTecnica: false,
etiqueta: "¡NUEVO!",
        desc: "<b>REF000</b><p>Activa de forma segura con credenciales corporativas y evita el uso de parches o cracks que comprometen la seguridad de tu PC.<p><b> </b>",
        caracteristicas: ["Ingresa la clave digital asignada y listo.", "Es transferible, puedes cámbiarla a otro equipo fácilmente.", "Instalala en equipos nuevos o existentes.", "Credenciales independientes - No se vincula a hardware especifico."],
        nota: "Se entrega la clave al usuario final, quien es responsable de su buen uso. La clave permanece operativa de manera indefinida, garantizando acceso continuo y seguridad en todo momento. <b>único pago.</b>",
        precio: "COP $20.000",
        video: "",
        fotos: ["img/p8-0.png", "img/p8-1.png"]
    },
    {
        id: 11,
        nombre: "Declaración de Renta",
        formato: "Servicio Profesional",
        mostrarTecnica: false,
etiqueta: "¡ACTIVA!",
        desc: "Brindamos consultoría integral para la elaboración y presentación de tu declaración de renta, asegurando el cumplimiento legal y la optimización de tus impuestos.",
        caracteristicas: ["Diagnóstico inicial de requisitos según topes de la DIAN.", "Análisis de deducciones y beneficios tributarios para pagar lo justo.", "Elaboración del borrador y formulario 110/210.", "Acompañamiento en el proceso de pago y firma electrónica.", "Entrega de informe detallado de la declaración presentada.", "Consulta en  https://webazure.dian.gov.co/consultarenta/"],
        nota: "El valor del servicio puede variar según la complejidad de la realidad financiera del contribuyente (cantidad de bienes, inversiones, etc.). <b>¡Contáctanos para una cotización personalizada!</b>",
        precio: "Desde COP $300.000",
        video: "https://webazure.dian.gov.co/consultarenta/",
        fotos: ["img/p11-0.png", "img/p11-1.png"]
    },
    {
        id: 9,
        nombre: "Anydesk V.6.0",
        formato: "Ejecutable .exe",
        mostrarTecnica: false,
etiqueta: "Activa",
        desc: "El software de escritorio remoto de alto rendimiento que permite compartir el escritorio sin latencia, un control remoto estable y una transmisión de datos rápida y segura entre dispositivos.<p><b> </b><p>",
        caracteristicas: ["Vea la pantalla de otro dispositivo o comparta su monitor con otros usuarios.", "Controle el teclado y el ratón de otro dispositivo o permita que otros usuarios interactúen con su pantalla.", "Acceda a su dispositivo remoto mediante contraseña sin tener que aceptar la sesión remota manualmente."],
        nota: "Se trata de una aplicación ejecutable (EXE) ha sido ajustada para mantener siempre la sesión activa y sin tiempos; la aplicación se mantiene operativa de forma indefinida. <b>Se recomienda no actualizar y mantener la versión inicial.</b>",
        precio: "COP $20.000",
        video: "",
        fotos: ["img/p9-0.png"]
    },
    {
        id: 10,
        nombre: "Plataformas/Membresías",
        formato: "Plataformas",
        mostrarTecnica: false,
etiqueta: "Activa",
        desc: "Te invitamos a visualizar nuestro catalogo de ocio, producción y entretenimiento con los mejores precios del mercado.<p><b> </b><p>",
        caracteristicas: ["Plataformas Streaming.", "Antivirus.", "IA.", "VPN.", "Diseño.", "Cursos.", "Juegos"],
        nota: "(https://acortar.link/Plataformax) Las membresias son en la mayoria mensuales y otras con oferta de hasta 3 y 12 meses. <b>Escribenos y podemos ampliar la información de interes.</b>",
        precio: "Desde COP $1.500",
        video: "https://acortar.link/Plataformax",
        fotos: ["img/p10-0.png"]
    }
];
